/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puskesmas;

import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wawan Chahyo Nugroho
 */
public class formPasien extends javax.swing.JDialog {
     DefaultTableModel modelTabel;
    /**
     * Creates new form formPasien
     */
    public formPasien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        String[] judul = {"No. Rumah","Nama","Alamat","Jenis Kelamin"};
        modelTabel = new DefaultTableModel(null, judul);
        tabelPasien.setModel(modelTabel);
        
        tampil();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        noRumah = new javax.swing.JTextField();
        nmPasien = new javax.swing.JTextField();
        almtPasien = new javax.swing.JTextField();
        jkel = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPasien = new javax.swing.JTable();
        butHapus = new javax.swing.JButton();
        butGanti = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Formulir Pasien");

        jLabel2.setText("No. Rumah");

        jLabel3.setText("Nama");

        jLabel4.setText("Alamat");

        jLabel5.setText("Jenis Kelamin");

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jkel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "L", "P" }));

        tabelPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPasien);

        butHapus.setText("Hapus");
        butHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHapusActionPerformed(evt);
            }
        });

        butGanti.setText("Ganti");
        butGanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGantiActionPerformed(evt);
            }
        });

        jLabel7.setText("Pencarian");

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(simpan))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(butHapus)
                                        .addGap(27, 27, 27)
                                        .addComponent(butGanti, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(noRumah)
                                        .addComponent(nmPasien)
                                        .addComponent(almtPasien, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(36, 36, 36)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noRumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nmPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(almtPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(butHapus)
                    .addComponent(butGanti))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
    try {
            MysqlDataSource server = new MysqlDataSource();
            server.setServerName("localhost");
            server.setUser("root");
            server.setPassword("");
            server.setPort(3306);
            server.setDatabaseName("puskesmas");
            Connection koneksi = server.getConnection();
            koneksi.prepareStatement("insert into pasien value ('"+noRumah.getText()+
                    "','"+nmPasien.getText()+
                    "','"+almtPasien.getText()+"','"+jkel.getSelectedItem()+"')").execute();
                    
            JOptionPane.showConfirmDialog(rootPane, "Data berhasil masuk!");
            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showConfirmDialog(rootPane, "Maaf data sudah ada!");
        }
    
    tampil();
    }//GEN-LAST:event_simpanActionPerformed

    private void tabelPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPasienMouseClicked
        if(tabelPasien.getRowCount()>0){
        noRumah.setText(tabelPasien.getValueAt(tabelPasien.getSelectedRow(), 0).toString());
        nmPasien.setText(tabelPasien.getValueAt(tabelPasien.getSelectedRow(), 1).toString());
        almtPasien.setText(tabelPasien.getValueAt(tabelPasien.getSelectedRow(), 2).toString());
        jkel.setSelectedItem(tabelPasien.getValueAt(tabelPasien.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_tabelPasienMouseClicked

    private void butHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHapusActionPerformed
        try {
            MysqlDataSource server = new MysqlDataSource();
            server.setServerName("localhost");
            server.setUser("root");
            server.setPassword("");
            server.setPort(3306);
            server.setDatabaseName("puskesmas");
            Connection koneksi = server.getConnection();
            koneksi.prepareStatement("delete from pasien where no_rumah='"+noRumah.getText()+"'").execute();
                    
            JOptionPane.showConfirmDialog(rootPane, "Data berhasil dihapus!");
           
           
            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showConfirmDialog(rootPane, "Maaf data sudah ada!");
           
        }
       
        tampil();
    }//GEN-LAST:event_butHapusActionPerformed

    private void butGantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGantiActionPerformed
        try {
            MysqlDataSource server = new MysqlDataSource();
            server.setServerName("localhost");
            server.setUser("root");
            server.setPassword("");
            server.setPort(3306);
            server.setDatabaseName("puskesmas");
            Connection koneksi = server.getConnection();
            koneksi.prepareStatement("update pasien set no_rumah='"+noRumah.getText()+
            "',nama='"+nmPasien.getText()+
            "',alamat='"+almtPasien.getText()+
            "',jenis_kelamin='"+jkel.getSelectedItem()+
            "' where no_rumah='"+tabelPasien.getValueAt(tabelPasien.getSelectedRow(), 0).toString()+"'").execute();
                    
            JOptionPane.showConfirmDialog(rootPane, "Data berhasil diganti!");
           
           
            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showConfirmDialog(rootPane, "Maaf data sudah ada!");
           
        }
       
        tampil();
    }//GEN-LAST:event_butGantiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int baris = modelTabel.getRowCount();
        for(int i=1; i<=baris; i++){
        modelTabel.removeRow(0);
        }
        
        try {
            MysqlDataSource server = new MysqlDataSource();
            server.setServerName("localhost");
            server.setUser("root");
            server.setPassword("");
            server.setPort(3306);
            server.setDatabaseName("puskesmas");
            Connection koneksi = server.getConnection();
            ResultSet rec = koneksi.prepareStatement("select * from pasien where "+
              "no_rumah like '%"+cari.getText()+"%' or "+
              "nama like '%"+cari.getText()+"%' or "+
              "alamat like '%"+cari.getText()+"%' or "+
              "jenis_kelamin like '%"+cari.getText()+"%'").executeQuery();
                    
            while(rec.next()){
            modelTabel.addRow(new String[]{
            rec.getString(1),rec.getString(2),rec.getString(3),rec.getString(4)
            });
            
            }
           
           
            
        } catch (Exception e) {
            System.out.println(e);
             
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                formPasien dialog = new formPasien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField almtPasien;
    private javax.swing.JButton butGanti;
    private javax.swing.JButton butHapus;
    private javax.swing.JTextField cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jkel;
    private javax.swing.JTextField nmPasien;
    private javax.swing.JTextField noRumah;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelPasien;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
       int baris = modelTabel.getRowCount();
        for(int i=1; i<=baris; i++){
        modelTabel.removeRow(0);
        }
        
        try {
            MysqlDataSource server = new MysqlDataSource();
            server.setServerName("localhost");
            server.setUser("root");
            server.setPassword("");
            server.setPort(3306);
            server.setDatabaseName("puskesmas");
            Connection koneksi = server.getConnection();
            ResultSet rec = koneksi.prepareStatement("select * from pasien").executeQuery();
                    
            while(rec.next()){
            modelTabel.addRow(new String[]{
            rec.getString(1),rec.getString(2),rec.getString(3),rec.getString(4)
            });
            
            }
           
           
            
        } catch (Exception e) {
            System.out.println(e);
    }

    
    }

}